# version = <=1.3.13

# [rewrite_local]
^https://fluxapi\.vvebo\.vip/v1/purchase/iap/subscription url script-analyze-echo-response https://raw.githubusercontent.com/gulangyushaonian/Script/refs/heads/main/Script/forward.js

# [mitm]
hostname = fluxapi.vvebo.vip
